module_type = "object"
private_key = "0x00"
network = "testnet"
modules_path = [
  "examples/contracts/navori/libs",
  "examples/contracts/navori/cpu-2",
  "examples/contracts/navori/cpu",
  "examples/contracts/navori/verifier",
]
addresses_name = ["lib_addr", "cpu_2_addr", "cpu_addr", "verifier_addr"]
yes = true
output_json = "test.json"
[deployed_addresses]
lib_addr = "0x123"
